INSERT INTO loc VALUES ('ABE','Agricultural And Biological Engineering');
INSERT INTO loc VALUES ('ADDL','Animal Disease Diagnostic Lab');
INSERT INTO loc VALUES ('ADM','Adm Agricultural Innovation Center');
INSERT INTO loc VALUES ('AERO','Aerospace Science Laboratory');
INSERT INTO loc VALUES ('AGAD','Agricultural Administration Building');
INSERT INTO loc VALUES ('AHF','Animal Holding Facility');
INSERT INTO loc VALUES ('AQUA','Boilermaker Aquatic Center');
INSERT INTO loc VALUES ('AR','Armory');
INSERT INTO loc VALUES ('ARMS','Armstrong (neil) Hall Of Engineering');
INSERT INTO loc VALUES ('ASB','Airport Service Building');
INSERT INTO loc VALUES ('ASTL','Animal Sciences Teaching Laboratory');
INSERT INTO loc VALUES ('BCC','Black Cultural Center');
INSERT INTO loc VALUES ('BCHM','Biochemistry Building');
INSERT INTO loc VALUES ('BIND','Bindley (William E.) Bioscience Center');
INSERT INTO loc VALUES ('BRK','Birck Nanotechnology Center');
INSERT INTO loc VALUES ('BRNG','Beering (steven C.) Hall Of Liberal Arts And Education');
INSERT INTO loc VALUES ('BRWN','Brown (Herbert C.) Laboratory Of Chemistry');
INSERT INTO loc VALUES ('BSG','Building Services And Grounds');
INSERT INTO loc VALUES ('CHAF','Chaffee Hall');
INSERT INTO loc VALUES ('CIVL','Civil Engineering Building');
INSERT INTO loc VALUES ('CL50','Class Of 1950 Lecture Hall');
INSERT INTO loc VALUES ('COMP','Composites Laboratory');
INSERT INTO loc VALUES ('CREC','France A. Córdova Recreational Sports Center');
INSERT INTO loc VALUES ('DANL','Daniel (William H.) Turfgrass Center');
INSERT INTO loc VALUES ('DAUC','Dauch (dick And Sandy) Alumni Center');
INSERT INTO loc VALUES ('DLR','Hall For Discovery And Learning Research');
INSERT INTO loc VALUES ('DOYL','Doyle (leo Philip) Laboratory');
INSERT INTO loc VALUES ('DYE','Pete Dye Clubhouse');
INSERT INTO loc VALUES ('EE','Electrical Engineering Building');
INSERT INTO loc VALUES ('EEL','Entomology Environmental Laboratory');
INSERT INTO loc VALUES ('EHSA','Equine Health Sciences Annex');
INSERT INTO loc VALUES ('EHSB','Equine Health Sciences Building');
INSERT INTO loc VALUES ('ELLT','Elliott (edward C.) Hall Of Music');
INSERT INTO loc VALUES ('ENAD','Engineering Administration Building');
INSERT INTO loc VALUES ('EXPT','Exponent');
INSERT INTO loc VALUES ('FOOD','Food Stores Building');
INSERT INTO loc VALUES ('FOPN','Flight Operations Building');
INSERT INTO loc VALUES ('FORS','Forestry Building');
INSERT INTO loc VALUES ('FPRD','Forest Products Building');
INSERT INTO loc VALUES ('FREH','Freehafer (lytle J.) Hall Of Administrative Services');
INSERT INTO loc VALUES ('FRNY','Forney Hall Of Chemical Engineering');
INSERT INTO loc VALUES ('FWLR','Fowler (Harriet O. And James M., Jr.) Memorial House');
INSERT INTO loc VALUES ('GCMB','Golf Course Maintenance Barn');
INSERT INTO loc VALUES ('GMF','Grounds Maintenance Facility');
INSERT INTO loc VALUES ('GRIS','Grissom Hall');
INSERT INTO loc VALUES ('GSMB','Golf Storage Maintenance Building');
INSERT INTO loc VALUES ('HAAS','Haas (Felix) Hall');
INSERT INTO loc VALUES ('HAMP','Delon And Elizabeth Hampton Hall Of Civil Engineering');
INSERT INTO loc VALUES ('HANS','Hansen (arthur G.) Life Sciences Research Building');
INSERT INTO loc VALUES ('HEAV','Heavilon Hall');
INSERT INTO loc VALUES ('HERL','Herrick Laboratories');
INSERT INTO loc VALUES ('HGR4-6','Hangars, Numbers 4 Through 6');
INSERT INTO loc VALUES ('HGRH','Horticulture Greenhouses');
INSERT INTO loc VALUES ('HIKS','Hicks (John W.) Undergraduate Library');
INSERT INTO loc VALUES ('HMMT','Hazardous Materials Management Trailer');
INSERT INTO loc VALUES ('HNLY','Bill And Sally Hanley Hall');
INSERT INTO loc VALUES ('HOCK','Wayne T. And Mary T. Hockmeyer Hall Of Structural Biology');
INSERT INTO loc VALUES ('HORT','Horticulture Building');
INSERT INTO loc VALUES ('HOVD','Hovde (Frederick L.) Hall Of Administration');
INSERT INTO loc VALUES ('HPN','Heating And Power Plant-north');
INSERT INTO loc VALUES ('IAF','Intercollegiate Athletic Facility');
INSERT INTO loc VALUES ('JNSN','Johnson (Helen R.) Hall Of Nursing');
INSERT INTO loc VALUES ('KCTR','Krannert Center For Executive Education And Research');
INSERT INTO loc VALUES ('KNOY','Knoy (maurice G.) Hall Of Technology');
INSERT INTO loc VALUES ('KRAN','Krannert Building');
INSERT INTO loc VALUES ('LAMB','Lambert (Ward L.) Fieldhouse And Gymnasium');
INSERT INTO loc VALUES ('LCC','Latino Cultural Center (600 Russell St.)');
INSERT INTO loc VALUES ('LILY','Lilly Hall Of Life Sciences');
INSERT INTO loc VALUES ('LMSB','Laboratory Materials Storage Building');
INSERT INTO loc VALUES ('LMST','Laboratory Materials Storage Trailer');
INSERT INTO loc VALUES ('LSA','Life Science Animal Building');
INSERT INTO loc VALUES ('LSPS','Life Science Plant And Soils Laboratory');
INSERT INTO loc VALUES ('LSR','Life Science Ranges (greenhouse And Service Building)');
INSERT INTO loc VALUES ('LWSN','Lawson (richard And Patricia) Computer Science Building');
INSERT INTO loc VALUES ('LYNN','Lynn (Charles J.) Hall Of Veterinary Medicine');
INSERT INTO loc VALUES ('MACK','Mackey (guy J.) Arena');
INSERT INTO loc VALUES ('MANN','Mann (gerald D. And Edna E.) Hall');
INSERT INTO loc VALUES ('MATH','Mathematical Sciences Building');
INSERT INTO loc VALUES ('ME','Mechanical Engineering Building');
INSERT INTO loc VALUES ('MGL','Michael Golden Engineering Laboratories And Shops');
INSERT INTO loc VALUES ('MJIS','Martin C. Jischke Hall Of Biomedical Engineering');
INSERT INTO loc VALUES ('MMDC','Materials Management And Distribution Center');
INSERT INTO loc VALUES ('MMS1','Materials Management Storage Building');
INSERT INTO loc VALUES ('MOLL','Mollenkopf Athletic Center');
INSERT INTO loc VALUES ('MRGN','Morgan (Burton D.) Center For Entrepreneurship');
INSERT INTO loc VALUES ('MRRT','Marriott Hall');
INSERT INTO loc VALUES ('MSEE','Materials And Electrical Engineering Building');
INSERT INTO loc VALUES ('MTHW','Matthews (mary L.) Hall');
INSERT INTO loc VALUES ('NAECC','Native American Educational And Cultural Center (south Campus Courts, Building B)');
INSERT INTO loc VALUES ('NLSN','Phillip E. Nelson Hall Of Food Science');
INSERT INTO loc VALUES ('NISW','Niswonger Aviation Technology Building');
INSERT INTO loc VALUES ('NUCL','Nuclear Engineering Building');
INSERT INTO loc VALUES ('OLMN','Ollman (melvin L.) Golfcart Barn');
INSERT INTO loc VALUES ('PAO','Pao (Yue-Kong) Hall Of Visual And Performing Arts');
INSERT INTO loc VALUES ('PFEN','Pfendler Hall (david C.) Of Agriculture');
INSERT INTO loc VALUES ('PFSB','Physical Facilities Service Building');
INSERT INTO loc VALUES ('PHYS','Physics Building');
INSERT INTO loc VALUES ('PJIS','Patty Jischke Early Care And Education Center');
INSERT INTO loc VALUES ('PMU','Purdue Memorial Union');
INSERT INTO loc VALUES ('PMUC','Purdue Memorial Union Club');
INSERT INTO loc VALUES ('POAN','Poultry Science Annex');
INSERT INTO loc VALUES ('POTR','Potter (a. A.) Engineering Center');
INSERT INTO loc VALUES ('POUL','Poultry Science Building');
INSERT INTO loc VALUES ('PRCE','Peirce Hall');
INSERT INTO loc VALUES ('PRSV','Printing Services Facility');
INSERT INTO loc VALUES ('PSYC','Psychological Sciences Building');
INSERT INTO loc VALUES ('PUSH','Purdue University Student Health Center');
INSERT INTO loc VALUES ('PVCC','Purdue Village Community Center');
INSERT INTO loc VALUES ('PWD','Parking Facilities');
INSERT INTO loc VALUES ('RAIL','American Railway Building');
INSERT INTO loc VALUES ('RAWL','Rawls (Jerry S.) Hall');
INSERT INTO loc VALUES ('REC','Recitation Building');
INSERT INTO loc VALUES ('RHPH','Heine (robert E.) Pharmacy Building');
INSERT INTO loc VALUES ('SC','Stanley Coulter Hall');
INSERT INTO loc VALUES ('SCCA-E','South Campus Courts, Buildings A-e');
INSERT INTO loc VALUES ('SCHL','Schleman (Helen B.) Hall Of Student Services');
INSERT INTO loc VALUES ('SCHO','Global Policy Research Institute (schowe House)');
INSERT INTO loc VALUES ('SCPA','Slayter Center Of Performing Arts');
INSERT INTO loc VALUES ('SMTH','Smith Hall');
INSERT INTO loc VALUES ('SOIL','Soil Erosion Laboratory, National');
INSERT INTO loc VALUES ('SPUR','Spurgeon (tom) Golf Training Center');
INSERT INTO loc VALUES ('SSOF','State Street Office Facility');
INSERT INTO loc VALUES ('STDM','Ross-ade Stadium (includes Ross-ade Pavilion [raP])');
INSERT INTO loc VALUES ('STEW','Stewart Center');
INSERT INTO loc VALUES ('STON','Stone (Winthrop E.) Hall');
INSERT INTO loc VALUES ('TEL','Telecommunications Building');
INSERT INTO loc VALUES ('TERM','Terminal Building');
INSERT INTO loc VALUES ('TERY','Terry (oliver P.) Memorial House');
INSERT INTO loc VALUES ('TH1-6','Tee-Hangars 1 Through 6');
INSERT INTO loc VALUES ('TREC','Turf Recreation Exercise Center');
INSERT INTO loc VALUES ('TSWF','Transportation Service Wash Facility');
INSERT INTO loc VALUES ('UNIV','University Hall');
INSERT INTO loc VALUES ('UPOB','Utility Plant Office Building');
INSERT INTO loc VALUES ('UPOF','Utility Plant Office Facility');
INSERT INTO loc VALUES ('UPSB','Utility Plant Storage Building');
INSERT INTO loc VALUES ('VA1','Veterinary Animal Isolation Building 1');
INSERT INTO loc VALUES ('VA2','Veterinary Animal Isolation Building 2');
INSERT INTO loc VALUES ('VCPR','Veterinary Center For Paralysis Research');
INSERT INTO loc VALUES ('VLAB','Veterinary Laboratory Animal Building');
INSERT INTO loc VALUES ('VMIF','Veterinary Medicine Isolation Facility');
INSERT INTO loc VALUES ('VOIN','Voinoff (samuel) Golf Pavilion');
INSERT INTO loc VALUES ('VPRB','Veterinary Pathobiology Research Building');
INSERT INTO loc VALUES ('VPTH','Veterinary Pathology Building');
INSERT INTO loc VALUES ('WADE','Wade (Walter W.) Utility Plant');
INSERT INTO loc VALUES ('WEST','Westwood (President’s Home)');
INSERT INTO loc VALUES ('WGLR','Women’s Golf Locker Room');
INSERT INTO loc VALUES ('WSLR','Whistler (roy L.) Hall Of Agricultural Research');
INSERT INTO loc VALUES ('WTHR','Wetherill (richard Benbridge) Laboratory Of Chemistry');
INSERT INTO loc VALUES ('YONG','Young (ernest C.) Hall');
INSERT INTO loc VALUES ('ZL1','Combustion Research Laboratory');
INSERT INTO loc VALUES ('ZL2','Gas Dynamics Research Laboratory');
INSERT INTO loc VALUES ('ZL3','High Pressure Research Laboratory');
INSERT INTO loc VALUES ('ZL4','Propulsion Research Laboratory');
INSERT INTO loc VALUES ('ZL5','Turbomachinery Fluid Dynamics Laboratory');
INSERT INTO loc VALUES ('CARY','Cary (Franklin Levering) Quadrangle');
INSERT INTO loc VALUES ('DUHM','Duhme (ophelia) Residence Hall');
INSERT INTO loc VALUES ('ERHT','Earhart (amelia) Residence Hall');
INSERT INTO loc VALUES ('FORD','Ford (Fred And Mary) Dining Court');
INSERT INTO loc VALUES ('FST','First Street Towers');
INSERT INTO loc VALUES ('HARR','Harrison (Benjamin) Residence Hall');
INSERT INTO loc VALUES ('HAWK','Hawkins (george A.) Hall');
INSERT INTO loc VALUES ('HILL','Hillenbrand Residence Hall');
INSERT INTO loc VALUES ('HLTP','Hilltop Apartments');
INSERT INTO loc VALUES ('MCUT','McCutcheon (John T.) Residence Hall');
INSERT INTO loc VALUES ('MRDH','Meredith (virginia C.) Residence Hall');
INSERT INTO loc VALUES ('OWEN','Owen (richard) Residence Hall');
INSERT INTO loc VALUES ('PVAB','Purdue Village Administration Building');
INSERT INTO loc VALUES ('PVIL','Purdue Village');
INSERT INTO loc VALUES ('PVP','Purdue Village Preschool');
INSERT INTO loc VALUES ('SHLY','Shealy (Frances M.) Residence Hall');
INSERT INTO loc VALUES ('SHRV','Shreve (eleanor B.) Residence Hall');
INSERT INTO loc VALUES ('SMLY','Smalley (John C.) Center For Housing And Food Services Administration, Residence Hall');
INSERT INTO loc VALUES ('VAWT','Vawter (everett B.) Residence Hall');
INSERT INTO loc VALUES ('WARN','Warren (martha E. And Eugene K.) Residence Hall');
INSERT INTO loc VALUES ('WDCT','Wiley Dining Court');
INSERT INTO loc VALUES ('WILY','Wiley (Harvey W.) Residence Hall');
INSERT INTO loc VALUES ('WOOD','Wood (elizabeth G. And William R.) Residence Hall');
INSERT INTO loc VALUES ('ALEX','John And Anna Margaret Ross Alexander Field');
INSERT INTO loc VALUES ('SOCC','Soccer Complex');
INSERT INTO loc VALUES ('SCHW','Dennis J. And Mary Lou Schwartz Tennis Center');
INSERT INTO loc VALUES ('PGG','Parking Garage, Grant Street');
INSERT INTO loc VALUES ('PGW','Parking Garage, Wood Street');
INSERT INTO loc VALUES ('PGM','Parking Garage, Marsteller Street');
INSERT INTO loc VALUES ('PGMD','Parking Garage, McCutcheon Drive');
INSERT INTO loc VALUES ('PGNW','Parking Garage, Northwestern Avenue (includes Visitor Information Center And Parking Services)');
INSERT INTO loc VALUES ('PGU','Parking Garage, University Street');
